apiVersion: v1
kind: Service
metadata:
  name: countries-service
  annotations:
    service.beta.kubernetes.io/linode-loadbalancer-throttle: "4"
  labels:
    app: countries-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 5000
      targetPort: 5000
  selector:
    app: countriesapp
  sessionAffinity: None
